# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52615353c4b7a8d3e75c3cfb9190067ce2eee8c6f1071586244b7abc7c2ba469648d6433c375b16c286141021beed630be90bbefa50e930d034b499e31e29494

test:
  secret_key_base: ed6ea636f9cef2e401abb1eaad8eaca14439150066c090c44a596fc2523fc73f745456f9d8c7c8a9a4b1a31e208e3bd2be5b4ec62c950968d508d4ad29113ccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
